/**
 * 物理器材图片解析
 *
 * 图片已统一迁出本目录，存放在 assets/resources/images/physical-equipment/<domain>/，
 * 运行时经 resource:// 协议（Electron 生产）或 BASE_URL/assets/resources（web）解析。
 * 本模块只保留解析逻辑 + 已落地图片 key 清单（用于占位符回退），不再用 import.meta.glob
 * 把图片字节编进 bundle。
 *
 * 命名格式：<domain>/<resourceCode>.webp
 * 新增/删除图片后，需同步更新下方 AVAILABLE_PHYSICAL_EQUIPMENT_IMAGE_KEYS。
 */
import type { PhysicalEquipmentDomain } from '@/types/physical-equipment'
import { resolvePresetResourceUrl } from '@/utils/preset-resource'

// 已落地到 assets/resources/images/physical-equipment/<domain>/ 的图片 key（<domain>/<resourceCode>）
const AVAILABLE_PHYSICAL_EQUIPMENT_IMAGE_KEYS = new Set<string>([
  'cognitive/cognitive-box01-seq001',
  'cognitive/cognitive-box01-seq002',
  'cognitive/cognitive-box01-seq003',
  'cognitive/cognitive-box02-seq004',
  'cognitive/cognitive-box02-seq005',
  'cognitive/cognitive-box03-seq006',
  'cognitive/cognitive-box03-seq007',
  'cognitive/cognitive-box04-seq008',
  'cognitive/cognitive-box04-seq009',
  'cognitive/cognitive-box04-seq010',
  'cognitive/cognitive-box05-seq011',
  'cognitive/cognitive-box05-seq012',
  'cognitive/cognitive-box05-seq013',
  'cognitive/cognitive-box06-seq014',
  'cognitive/cognitive-box06-seq015',
  'cognitive/cognitive-box07-seq016',
  'cognitive/cognitive-box07-seq017',
  'cognitive/cognitive-box08-seq018',
  'cognitive/cognitive-box08-seq019',
  'cognitive/cognitive-box08-seq020',
  'cognitive/cognitive-box09-seq021',
  'cognitive/cognitive-box09-seq022',
  'cognitive/cognitive-box10-seq023',
  'cognitive/cognitive-box10-seq024',
  'cognitive/cognitive-box10-seq025',
  'cognitive/cognitive-box11-seq026',
  'cognitive/cognitive-box11-seq027',
  'cognitive/cognitive-box12-seq028',
  'cognitive/cognitive-box12-seq029',
  'cognitive/cognitive-box13-seq030',
  'cognitive/cognitive-box14-seq031',
  'cognitive/cognitive-box14-seq032',
  'cognitive/cognitive-box14-seq033',
  'cognitive/cognitive-box15-seq034',
  'cognitive/cognitive-box15-seq035',
  'cognitive/cognitive-box15-seq036',
  'cognitive/cognitive-box16-seq037',
  'cognitive/cognitive-box16-seq038',
  'cognitive/cognitive-box17-seq039',
  'cognitive/cognitive-box17-seq040',
  'cognitive/cognitive-box17-seq041',
  'cognitive/cognitive-box18-seq042',
  'cognitive/cognitive-box18-seq043',
  'cognitive/cognitive-box19-seq044',
  'cognitive/cognitive-box19-seq045',
  'cognitive/cognitive-box20-seq046',
  'cognitive/cognitive-box21-seq047',
  'cognitive/cognitive-box22-seq048',
  'cognitive/cognitive-box22-seq049',
  'cognitive/cognitive-box23-seq050',
  'cognitive/cognitive-box23-seq051',
  'cognitive/cognitive-box23-seq052',
  'daily-living/daily-living-box01-seq001',
  'daily-living/daily-living-box01-seq002',
  'daily-living/daily-living-box01-seq003',
  'daily-living/daily-living-box02-seq004',
  'daily-living/daily-living-box02-seq004-a',
  'daily-living/daily-living-box04-seq006',
  'daily-living/daily-living-box04-seq007',
  'daily-living/daily-living-box04-seq008',
  'daily-living/daily-living-box05-seq009',
  'daily-living/daily-living-box06-seq010',
  'daily-living/daily-living-box07-seq011',
  'daily-living/daily-living-box08-seq012',
  'daily-living/daily-living-box09-seq013',
  'daily-living/daily-living-box09-seq013-a',
  'daily-living/daily-living-box10-seq014',
  'daily-living/daily-living-box11-seq015',
  'daily-living/daily-living-box11-seq015-a',
  'daily-living/daily-living-box13-seq016',
  'daily-living/daily-living-box14-seq017',
  'daily-living/daily-living-box15-seq018',
  'daily-living/daily-living-box15-seq018-a',
  'daily-living/daily-living-box16-seq019',
  'daily-living/daily-living-box17-seq020',
  'daily-living/daily-living-box18-seq021',
  'daily-living/daily-living-box18-seq021-a',
  'daily-living/daily-living-box18-seq021-b',
  'daily-living/daily-living-box18-seq021-c',
  'daily-living/daily-living-box18-seq021-d',
  'daily-living/daily-living-box19-seq022',
  'daily-living/daily-living-box20-seq023',
  'daily-living/daily-living-box21-seq024',
  'daily-living/daily-living-box22-seq025',
  'daily-living/daily-living-box23-seq026',
  'daily-living/daily-living-box24-seq027',
  'daily-living/daily-living-box27-seq031',
  'daily-living/daily-living-box28-seq032',
  'daily-living/daily-living-box28-seq033',
  'daily-living/daily-living-box28-seq034',
  'daily-living/daily-living-box29-seq035',
  'daily-living/daily-living-box30-seq036',
  'daily-living/daily-living-box31-seq037',
  'daily-living/daily-living-box32-seq038',
  'daily-living/daily-living-box32-seq038-a',
  'daily-living/daily-living-box33-seq039',
  'daily-living/daily-living-box33-seq039-a',
  'daily-living/daily-living-box33-seq039-b',
  'daily-living/daily-living-box33-seq039-c',
  'daily-living/daily-living-box34-seq040',
  'daily-living/daily-living-box34-seq040-a',
  'daily-living/daily-living-box34-seq040-b',
  'daily-living/daily-living-box35-seq041',
  'daily-living/daily-living-box35-seq041-a',
  'daily-living/daily-living-box35-seq041-b',
  'daily-living/daily-living-box36-seq042',
  'daily-living/daily-living-box36-seq042-a',
  'daily-living/daily-living-box37-seq043',
  'daily-living/daily-living-box38-seq044',
  'daily-living/daily-living-box39-seq045',
  'daily-living/daily-living-box39-seq045-a',
  'daily-living/daily-living-box39-seq045-b',
  'daily-living/daily-living-box40-seq046',
  'emotional-regulation/emotional-regulation-box01-seq001',
  'emotional-regulation/emotional-regulation-box01-seq002',
  'emotional-regulation/emotional-regulation-box01-seq003',
  'emotional-regulation/emotional-regulation-box02-seq004',
  'emotional-regulation/emotional-regulation-box02-seq005',
  'emotional-regulation/emotional-regulation-box02-seq006',
  'emotional-regulation/emotional-regulation-box03-seq008',
  'emotional-regulation/emotional-regulation-box05-seq010',
  'emotional-regulation/emotional-regulation-box06-seq011',
  'emotional-regulation/emotional-regulation-box07-seq012',
  'emotional-regulation/emotional-regulation-box08-seq013',
  'emotional-regulation/emotional-regulation-box09-seq014',
  'emotional-regulation/emotional-regulation-box13-seq018',
  'emotional-regulation/emotional-regulation-box14-seq019',
  'emotional-regulation/emotional-regulation-box15-seq020',
  'emotional-regulation/emotional-regulation-box16-seq021',
  'emotional-regulation/emotional-regulation-box17-seq022',
  'emotional-regulation/emotional-regulation-box18-seq023',
  'emotional-regulation/emotional-regulation-box18-seq024',
  'emotional-regulation/emotional-regulation-box19-seq025',
  'emotional-regulation/emotional-regulation-box19-seq026',
  'emotional-regulation/emotional-regulation-box20-seq027',
  'emotional-regulation/emotional-regulation-box20-seq027-a',
  'emotional-regulation/emotional-regulation-box20-seq027-b',
  'emotional-regulation/emotional-regulation-box20-seq027-c',
  'emotional-regulation/emotional-regulation-box20-seq027-d',
  'emotional-regulation/emotional-regulation-box21-seq028',
  'emotional-regulation/emotional-regulation-box21-seq029',
  'emotional-regulation/emotional-regulation-box22-seq030',
  'emotional-regulation/emotional-regulation-box23-seq031',
  'emotional-regulation/emotional-regulation-box23-seq032',
  'emotional-regulation/emotional-regulation-box24-seq033',
  'emotional-regulation/emotional-regulation-box25-seq034',
  'emotional-regulation/emotional-regulation-box25-seq034-a',
  'emotional-regulation/emotional-regulation-box26-seq035',
  'emotional-regulation/emotional-regulation-box27-seq036',
  'emotional-regulation/emotional-regulation-box27-seq036-a',
  'emotional-regulation/emotional-regulation-box28-seq037',
  'emotional-regulation/emotional-regulation-box29-seq038',
  'emotional-regulation/emotional-regulation-box30-seq039',
  'fine-motor/fine-motor-box01-seq001',
  'fine-motor/fine-motor-box01-seq002',
  'fine-motor/fine-motor-box02-seq003',
  'fine-motor/fine-motor-box02-seq004',
  'fine-motor/fine-motor-box03-seq006',
  'fine-motor/fine-motor-box03-seq015',
  'fine-motor/fine-motor-box04-seq007',
  'fine-motor/fine-motor-box05-seq008',
  'fine-motor/fine-motor-box06-seq009',
  'fine-motor/fine-motor-box07-seq010',
  'fine-motor/fine-motor-box07-seq011',
  'fine-motor/fine-motor-box08-seq012',
  'fine-motor/fine-motor-box08-seq013',
  'fine-motor/fine-motor-box09-seq014',
  'fine-motor/fine-motor-box10-seq016',
  'fine-motor/fine-motor-box11-seq017',
  'fine-motor/fine-motor-box11-seq018',
  'fine-motor/fine-motor-box12-seq019',
  'fine-motor/fine-motor-box13-seq020',
  'fine-motor/fine-motor-box14-seq021',
  'fine-motor/fine-motor-box14-seq022',
  'fine-motor/fine-motor-box15-seq023',
  'fine-motor/fine-motor-box16-seq024',
  'fine-motor/fine-motor-box17-seq025',
  'fine-motor/fine-motor-box18-seq026',
  'fine-motor/fine-motor-box19-seq027',
  'fine-motor/fine-motor-box20-seq028',
  'fine-motor/fine-motor-box21-seq029',
  'fine-motor/fine-motor-box23-seq031',
  'fine-motor/fine-motor-box24-seq032',
  'fine-motor/fine-motor-box25-seq033',
  'fine-motor/fine-motor-box26-seq034',
  'social-communication/social-communication-box01-seq001',
  'social-communication/social-communication-box01-seq002',
  'social-communication/social-communication-box02-seq003',
  'social-communication/social-communication-box02-seq004',
  'social-communication/social-communication-box03-seq005',
  'social-communication/social-communication-box03-seq006',
  'social-communication/social-communication-box03-seq007',
  'social-communication/social-communication-box04-seq008',
  'social-communication/social-communication-box04-seq009',
  'social-communication/social-communication-box05-seq010',
  'social-communication/social-communication-box05-seq011',
  'social-communication/social-communication-box05-seq012',
  'social-communication/social-communication-box06-seq013',
  'social-communication/social-communication-box06-seq014',
  'social-communication/social-communication-box07-seq015',
  'social-communication/social-communication-box08-seq017',
  'social-communication/social-communication-box09-seq018',
  'social-communication/social-communication-box10-seq019',
  'social-communication/social-communication-box11-seq020',
  'social-communication/social-communication-box12-seq021',
  'social-communication/social-communication-box13-seq022',
  'social-communication/social-communication-box14-seq023',
  'social-communication/social-communication-box15-seq024',
  'social-communication/social-communication-box16-seq025',
  'social-communication/social-communication-box17-seq026',
  'social-communication/social-communication-box18-seq027',
  'social-communication/social-communication-box19-seq028',
  'social-communication/social-communication-box20-seq029',
  'social-communication/social-communication-box21-seq030',
  'social-communication/social-communication-box21-seq031',
  'social-communication/social-communication-box22-seq032',
  'social-communication/social-communication-box23-seq033',
  'social-communication/social-communication-box24-seq034',
  'social-communication/social-communication-box25-seq035',
  'social-communication/social-communication-box26-seq036',
  'social-communication/social-communication-box27-seq037',
  'social-communication/social-communication-box28-seq038',
  'social-communication/social-communication-box28-seq039',
  'social-communication/social-communication-box29-seq040',
  'social-communication/social-communication-box29-seq041',
  'social-communication/social-communication-box29-seq042',
  'social-communication/social-communication-box30-seq043',
  'social-communication/social-communication-box30-seq044',
  'social-communication/social-communication-box30-seq045',
  'social-communication/social-communication-box31-seq046',
  'social-communication/social-communication-box32-seq047',
  'social-communication/social-communication-box33-seq048',
  'social-communication/social-communication-box34-seq049',
  'soothing-aids/soothing-aids-box01-seq001',
  'soothing-aids/soothing-aids-box02-seq002',
  'soothing-aids/soothing-aids-box03-seq003',
  'soothing-aids/soothing-aids-box04-seq004',
  'soothing-aids/soothing-aids-box05-seq005',
  'soothing-aids/soothing-aids-box07-seq007',
  'soothing-aids/soothing-aids-box08-seq008',
  'soothing-aids/soothing-aids-box08-seq009',
  'soothing-aids/soothing-aids-box09-seq010',
  'soothing-aids/soothing-aids-box10-seq011',
  'soothing-aids/soothing-aids-box11-seq013',
  'soothing-aids/soothing-aids-box12-seq014',
  'soothing-aids/soothing-aids-box13-seq015',
  'soothing-aids/soothing-aids-box13-seq016',
  'soothing-aids/soothing-aids-box13-seq017',
  'soothing-aids/soothing-aids-box14-seq018',
  'soothing-aids/soothing-aids-box15-seq019',
  'soothing-aids/soothing-aids-box15-seq021',
  'soothing-aids/soothing-aids-box16-seq020',
  'soothing-aids/soothing-aids-box17-seq022',
  'soothing-aids/soothing-aids-box18-seq023',
  'soothing-aids/soothing-aids-box19-seq024',
  'soothing-aids/soothing-aids-box20-seq025',
  'soothing-aids/soothing-aids-box21-seq026',
  'soothing-aids/soothing-aids-box22-seq027',
  'soothing-aids/soothing-aids-box22-seq028',
  'soothing-aids/soothing-aids-box23-seq029',
  'soothing-aids/soothing-aids-box23-seq030',
  'soothing-aids/soothing-aids-box24-seq031',
  'soothing-aids/soothing-aids-box25-seq032',
  'soothing-aids/soothing-aids-box26-seq033',
  'soothing-aids/soothing-aids-box26-seq034',
  'soothing-aids/soothing-aids-box27-seq035',
  'soothing-aids/soothing-aids-box28-seq036',
])

const DOMAIN_COLORS: Record<PhysicalEquipmentDomain, string> = {
  'emotional-regulation': '#e67e22',
  'social-communication': '#3498db',
  'fine-motor': '#27ae60',
  'soothing-aids': '#8e44ad',
  'daily-living': '#e74c3c',
  'cognitive': '#13c2c2',
}

function generatePlaceholderUrl(domain: PhysicalEquipmentDomain, name: string): string {
  const color = DOMAIN_COLORS[domain] || '#95a5a6'
  const firstChar = name.trim().charAt(0) || '?'

  const svg = `
    <svg width="128" height="128" xmlns="http://www.w3.org/2000/svg">
      <rect width="128" height="128" rx="24" fill="${color}"/>
      <text x="64" y="78" font-size="48" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-weight="bold">${firstChar}</text>
    </svg>
  `.trim()

  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}

export function getPhysicalEquipmentImageUrl(
  domain: PhysicalEquipmentDomain,
  resourceCode: string,
  name: string
): string {
  const key = `${domain}/${resourceCode}`

  if (AVAILABLE_PHYSICAL_EQUIPMENT_IMAGE_KEYS.has(key)) {
    return resolvePresetResourceUrl(`images/physical-equipment/${key}.webp`)
  }

  return generatePlaceholderUrl(domain, name)
}
