import type { TrainingResourceCopyRow } from '@/utils/training-resource-copy'

// Generated from docs/references/resource-copy/2026-03-30-training-resource-copy.csv
// Do not edit this file manually.
export const TRAINING_RESOURCE_COPY_ROWS: TrainingResourceCopyRow[] = [

]

const TRAINING_RESOURCE_COPY_MAP = new Map(
  TRAINING_RESOURCE_COPY_ROWS.map((row) => [row.resourceKey, row] as const)
)

export function getTrainingResourceCopyOverride(resourceKey: string): TrainingResourceCopyRow | null {
  return TRAINING_RESOURCE_COPY_MAP.get(resourceKey) || null
}
